---
version: '3'
services:
  validata:
    env_file:
      - .env
    build:
      context: ./
    container_name: validata_$ENV_NAME
    environment:
      - BADGE_CONFIG_URL=https://gitlab.com/validata-table/validata-badge/raw/master/badge_conf.toml
      - CONFIG=config.yaml
      - CONFIG_FILE=config.yaml
      - HOMEPAGE_CONFIG_FILE=homepage_config.json
    ports:
      - $PORT_NUMBER:5000
