---
version: '3'
services:
  validata_api:
    env_file:
      - .env
    image:
      registry.gitlab.com/validata-table/validata-table/validata-table-api:v0.11.3
    container_name: validata-api_$ENV_NAME
    ports:
      - $PORT_NUMBER_API:5600
